---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: usagi
description: Pantheon Fedora Atomic image with batteries included. (not ready)

base-image: ghcr.io/ublue-os/base-main

alt-tags:
  - latest

image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - example.sh

  - type: systemd
    system:
      enabled:
        - ublue-lightdm-workaround.service

  - type: dnf
    repos:
      copr:
        - garaevdi/pantheon-rpm
      nonfree: rpmfusion
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      cleanup: true

    install:
      packages:
        # desktop stuff
        - appcenter
        - elementary-code
        - elementary-calendar
        - elementary-dock
        - elementary-greeter
        - elementary-mail
        - elementary-monitor
        - elementary-photos
        - elementary-settings
        - elementary-shortcut-overlay
        - elementary-sideload
        - elementary-terminal
        - elementary-files
        - elementary-files-portal
        - elementary-onboarding
        - gala
        - gcr
        - PackageKit-bootc
        - pantheon-agent-polkit
        - pantheon-session-settings
        - plymouth-theme-elementary
        - switchboard
        - wingpanel
        - xdg-desktop-portal-pantheon

        # terminal stuff
        - fish
        - starship
        - eza
        - bat
        - btop
        - fastfetch
        - zoxide
        - fzf
        - ripgrep
        - fd-find

    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - wingpanel-indicator-a11y # archived at upstream

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          title: appcenter
          url: https://flatpak.elementary.io/repo.flatpakrepo

        install:
          - io.elementary.calculator
          - io.elementary.calendar
          - io.elementary.camera
          - io.elementary.capnet-assist
          - io.elementary.contacts
          - io.elementary.iconbrowser
          - io.elementary.maps
          - io.elementary.mail
          - io.elementary.music
          - io.elementary.photos
          - io.elementary.screenshot
          - io.elementary.tasks
          - io.elementary.videos
          - org.gnome.Epiphany
          - org.gnome.Evince
          - org.gnome.FileRoller
          - org.gnome.font-viewer

  - type: brew
    auto-update: true
    auto-upgrade: true

  - type: os-release
    properties:
      ID: usagi
      ID_LIKE: fedora
      NAME: Usagi
      PRETTY_NAME: "Usagi"
      VERSION: "44"
      VERSION_CODENAME: usagi
      HOME_URL: "https://github.com/fuwaflow/usagi"

  - type: initramfs

  - type: signing
