# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>

name: cocoa-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: systemd
    system:
      enabled:
        - ublue-lightdm-workaround.service
  - type: dnf
    repos:
      copr:
        - garaevdi/pantheon-rpm
      nonfree: rpmfusion
      cleanup: true
    install:
      packages:
        - appcenter
        - elementary-code
        - elementary-calendar
        - elementary-dock
        - elementary-files
        - elementary-files-portal
        - elementary-greeter
        - elementary-mail
        - elementary-monitor
        - elementary-photos
        - elementary-settings
        - elementary-shortcut-overlay
        - elementary-terminal
        - gala
        - gcr
        - pantheon-agent-polkit
        - pantheon-session-settings
        - switchboard
        - wingpanel
        - xdg-desktop-portal-pantheon
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-ugly
        - gstreamer1-plugin-openh264
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - wingpanel-indicator-a11y
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          title: elementary
          url: https://flatpak.elementary.io/repo.flatpakrepo
        install:
          - io.elementary.camera/x86_64/stable
          - io.elementary.capnet-assist/x86_64/stable
          - io.elementary.contacts/x86_64/stable
          - io.elementary.iconbrowser/x86_64/stable
          - io.elementary.maps/x86_64/stable
          - io.elementary.music/x86_64/stable
          - io.elementary.screenshot/x86_64/stable
          - io.elementary.tasks/x86_64/stable
          - io.elementary.videos/x86_64/stable
          - org.gnome.Epiphany/x86_64/stable
          - org.gnome.Evince/x86_64/stable
          - org.gnome.FileRoller/x86_64/stable
          - org.gnome.font-viewer/x86_64/stable
      - notify: false
        scope: system
        install:
          - org.mozilla.firefox
          - org.mozilla.Thunderbird
  - type: signing
